### ISSUE TITLE
Motor board config loading

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#3]
I think the config loading should be documented somewhere in this repo.
Or even better, write a python package with tools to interact with a motor board (like we have for the CAN bootloader).

**Comment by antoinealb** [comment]
I have started working on it as a part of my journey to clean UAVCAN. I plan to modify the motor board firmware so that it stores its config in flash, then write a python script to write the config to all boards from the USB dongle. Everything should happen through UAVCAN's parameter service, which will allow us to deprecate our custom mechanism.

**Comment by SyrianSpock** [comment]
@antoinealb This is still in progress ?

**Comment by antoinealb** [comment]
It was still controversial when we discussed it last time, but I think most of the team was in favor of it. Haven't made progress on the code front, but still happy to do it.

**Comment by SyrianSpock** [comment]
I still think it's a good idea to do it.

**Comment by SyrianSpock** [comment]
It's getting painful to debug things on the master board as it panics when we reboot it from gdb (so the bus is not rebooted and the motor config setting times out). I think we should implement this soon.
